# Generated by Django 3.0.8 on 2020-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('sale', models.BooleanField(default=False)),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
            ],
        ),
    ]
